name: 'Yandex Serverless Action'
description: 'Deploy new version of Serverless function to Yandex Cloud'
author: 'Goodsmileduck'
branding:
  color: 'blue'
  icon: 'upload-cloud'
inputs:
  description:
    description: 'Function description'
    default: ''
    required: false
  token:
    description: 'OAuth token'
    default: ''
    required: true
  accessKeyId:
    description: 'Yandex AWS Access Key Id when s3 bucket used'
    default: ''
    required: false
  secretAccessKey:
    description: 'Yandex AWS Secret Access Key when s3 bucket used'
    default: ''
    required: false
  function_id:
    description: 'Function Id in Yandex Cloud'
    default: ''
    required: true
  bucket:
    description: 'S3 bucket name for code'
    default: ''
    required: false
  runtime:
    description: 'Runtime for function'
    default: ''
    required: true
  entrypoint:
    description: 'Entrypoint for function'
    default: ''
    required: true
  source:
    description: 'Source directory for cloud function in git repo'
    default: '.'
    required: false
  exclude:
    description: 'Exclude patterns (comma separated) for source directory'
    default: ''
    required: false
  memory:
    description: 'Memory in Mb'
    default: '128'
    required: false
  environment:
    description: 'Env variables for function'
    default: ''
    required: false
  execution_timeout:
    description: 'Execution timeout'
    default: '5'
    required: false
  service_account:
    description: 'Service account for function'
    default: ''
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
